// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelSystem.Services.Data;

#nullable disable

namespace TravelSystem.Services.Migrations
{
    [DbContext(typeof(TravelDbContext))]
    partial class TravelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelSystem.Core.Entities.Student", b =>
                {
                    b.Property<string>("PersonalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonalId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("TravelSystem.Core.Entities.StudentLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TravelSystem.Core.Entities.Teacher", b =>
                {
                    b.Property<string>("PersonalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonalId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("TravelSystem.Core.Entities.StudentLocation", b =>
                {
                    b.OwnsOne("TravelSystem.Core.Entities.GeoCoordinates", "Coordinates", b1 =>
                        {
                            b1.Property<int>("StudentLocationId")
                                .HasColumnType("int");

                            b1.HasKey("StudentLocationId");

                            b1.ToTable("Locations");

                            b1.WithOwner()
                                .HasForeignKey("StudentLocationId");

                            b1.OwnsOne("TravelSystem.Core.Entities.CoordinateDetail", "Latitude", b2 =>
                                {
                                    b2.Property<int>("GeoCoordinatesStudentLocationId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Degrees")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Minutes")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Seconds")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("GeoCoordinatesStudentLocationId");

                                    b2.ToTable("Locations");

                                    b2.WithOwner()
                                        .HasForeignKey("GeoCoordinatesStudentLocationId");
                                });

                            b1.OwnsOne("TravelSystem.Core.Entities.CoordinateDetail", "Longitude", b2 =>
                                {
                                    b2.Property<int>("GeoCoordinatesStudentLocationId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Degrees")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Minutes")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Seconds")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("GeoCoordinatesStudentLocationId");

                                    b2.ToTable("Locations");

                                    b2.WithOwner()
                                        .HasForeignKey("GeoCoordinatesStudentLocationId");
                                });

                            b1.Navigation("Latitude")
                                .IsRequired();

                            b1.Navigation("Longitude")
                                .IsRequired();
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
